import { SortOrder } from "../../util/SortOrder";

export type GameOrderByInput = {
  advanced?: SortOrder;
  bet?: SortOrder;
  bids?: SortOrder;
  cask?: SortOrder;
  categoryId?: SortOrder;
  categoryTemp?: SortOrder;
  chanceFirepot1?: SortOrder;
  chanceFirepot2?: SortOrder;
  chanceFirepot3?: SortOrder;
  createdAt?: SortOrder;
  currentRtp?: SortOrder;
  denomination?: SortOrder;
  developer?: SortOrder;
  device?: SortOrder;
  featured?: SortOrder;
  fireCount1?: SortOrder;
  fireCount2?: SortOrder;
  fireCount3?: SortOrder;
  gamebank?: SortOrder;
  id?: SortOrder;
  isActive?: SortOrder;
  jackpotGroupId?: SortOrder;
  jpgId?: SortOrder;
  linesPercentConfigBonus?: SortOrder;
  linesPercentConfigBonusBonus?: SortOrder;
  linesPercentConfigSpin?: SortOrder;
  linesPercentConfigSpinBonus?: SortOrder;
  name?: SortOrder;
  originalId?: SortOrder;
  popularity?: SortOrder;
  providerId?: SortOrder;
  rezerv?: SortOrder;
  rtpStatIn?: SortOrder;
  rtpStatOut?: SortOrder;
  scaleMode?: SortOrder;
  shopId?: SortOrder;
  slotViewState?: SortOrder;
  standardRtp?: SortOrder;
  statIn?: SortOrder;
  statOut?: SortOrder;
  title?: SortOrder;
  updatedAt?: SortOrder;
  view?: SortOrder;
  vipLevel?: SortOrder;
};
