import { AccountListRelationFilter } from "../account/AccountListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { StringFilter } from "../../util/StringFilter";
import { StatGameListRelationFilter } from "../statGame/StatGameListRelationFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { MessageListRelationFilter } from "../message/MessageListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

export type PersonWhereInput = {
  accounts?: AccountListRelationFilter;
  activeAccountId?: StringNullableFilter;
  activeShopId?: StringNullableFilter;
  avatar?: StringNullableFilter;
  cashtag?: StringNullableFilter;
  createdAt?: DateTimeFilter;
  deletedAt?: DateTimeNullableFilter;
  email?: StringNullableFilter;
  emailConfirmed?: BooleanNullableFilter;
  embeddings?: JsonFilter;
  favorites?: StringFilter;
  gameStats?: StatGameListRelationFilter;
  id?: StringFilter;
  isDeleted?: BooleanFilter;
  isFirstDeposit?: BooleanNullableFilter;
  isSupended?: BooleanNullableFilter;
  lastSignInAt?: DateTimeNullableFilter;
  messages?: MessageListRelationFilter;
  password?: StringNullableFilter;
  personInfo?: JsonFilter;
  personname?: StringNullableFilter;
  phone?: StringNullableFilter;
  phoneConfirmed?: BooleanNullableFilter;
  resetPasswordToken?: StringNullableFilter;
  updatedAt?: DateTimeFilter;
  vipLevel?: IntNullableFilter;
};
