import { AccountListRelationFilter } from "../account/AccountListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
import { BetListRelationFilter } from "../bet/BetListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FishBankWhereUniqueInput } from "../fishBank/FishBankWhereUniqueInput";
import { GameBankWhereUniqueInput } from "../gameBank/GameBankWhereUniqueInput";
import { StatGameListRelationFilter } from "../statGame/StatGameListRelationFilter";
import { GameListRelationFilter } from "../game/GameListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { OpenShiftListRelationFilter } from "../openShift/OpenShiftListRelationFilter";
import { ProductListRelationFilter } from "../product/ProductListRelationFilter";
import { BalanceTransactionListRelationFilter } from "../balanceTransaction/BalanceTransactionListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";

export type ShopWhereInput = {
  accounts?: AccountListRelationFilter;
  balance?: IntFilter;
  bets?: BetListRelationFilter;
  code?: StringNullableFilter;
  createdAt?: DateTimeFilter;
  description?: StringNullableFilter;
  facialRecognition?: IntNullableFilter;
  fishBank?: FishBankWhereUniqueInput;
  gameBank?: GameBankWhereUniqueInput;
  gameStatsAccount?: StatGameListRelationFilter;
  games?: GameListRelationFilter;
  id?: StringFilter;
  isActive?: BooleanNullableFilter;
  isMfaRequired?: BooleanNullableFilter;
  name?: StringNullableFilter;
  openShifts?: OpenShiftListRelationFilter;
  product?: ProductListRelationFilter;
  shopSettingsId?: StringNullableFilter;
  tenantId?: StringNullableFilter;
  transactions?: BalanceTransactionListRelationFilter;
  updatedAt?: DateTimeNullableFilter;
  url?: StringNullableFilter;
};
