/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  Max,
  IsString,
  MaxLength,
  IsEnum,
  ValidateNested,
  IsOptional,
  IsBoolean,
} from "class-validator";

import { EnumBalanceTransactionChannel } from "./EnumBalanceTransactionChannel";
import { EnumBalanceTransactionDirection } from "./EnumBalanceTransactionDirection";
import { EnumBalanceTransactionPaymentMethod } from "./EnumBalanceTransactionPaymentMethod";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import { Type } from "class-transformer";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { ShopWhereUniqueInput } from "../../shop/base/ShopWhereUniqueInput";
import { EnumBalanceTransactionStatus } from "./EnumBalanceTransactionStatus";
import { EnumBalanceTransactionType } from "./EnumBalanceTransactionType";

@InputType()
class BalanceTransactionCreateInput {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  amount!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  bonusIdUsed!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  cashierAccountId!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  cashierAvatar!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  cashierId!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  cashiername!: string;

  @ApiProperty({
    required: true,
    enum: EnumBalanceTransactionChannel,
  })
  @IsEnum(EnumBalanceTransactionChannel)
  @Field(() => EnumBalanceTransactionChannel)
  channel!:
    | "WALLET"
    | "COINBASE"
    | "BTCPAYSERVER"
    | "CASHAPP"
    | "INSTORE"
    | "PINCODE";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  currency!: string;

  @ApiProperty({
    required: true,
    enum: EnumBalanceTransactionDirection,
  })
  @IsEnum(EnumBalanceTransactionDirection)
  @Field(() => EnumBalanceTransactionDirection)
  direction!: "ADD" | "OUT";

  @ApiProperty({
    required: true,
    enum: EnumBalanceTransactionPaymentMethod,
  })
  @IsEnum(EnumBalanceTransactionPaymentMethod)
  @Field(() => EnumBalanceTransactionPaymentMethod)
  paymentMethod!: "CASHAPP" | "INSTORE" | "VENMO" | "CRYPTO";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  personAvatar!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  personId!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  personname!: string;

  @ApiProperty({
    required: true,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @Field(() => AccountWhereUniqueInput)
  playerAccount!: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  playerAccountBalanceAfterTransaction?: number | null;

  @ApiProperty({
    required: true,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @Field(() => ProductWhereUniqueInput)
  product!: ProductWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  salesCommission?: number | null;

  @ApiProperty({
    required: true,
    type: () => ShopWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ShopWhereUniqueInput)
  @Field(() => ShopWhereUniqueInput)
  shop!: ShopWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  shopBalanceAfterTransaction?: number | null;

  @ApiProperty({
    required: true,
    enum: EnumBalanceTransactionStatus,
  })
  @IsEnum(EnumBalanceTransactionStatus)
  @Field(() => EnumBalanceTransactionStatus)
  status!:
    | "PENDING_PAYMENT"
    | "PAYMENT_FAILED"
    | "EXPIRED"
    | "CANCELLED_BY_PLAYER"
    | "CANCELLED_BY_SHOP"
    | "CANCELLED_BY_SYSTEM"
    | "SUCCEEDED";

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  totalInCents!: number;

  @ApiProperty({
    required: true,
    enum: EnumBalanceTransactionType,
  })
  @IsEnum(EnumBalanceTransactionType)
  @Field(() => EnumBalanceTransactionType)
  type!:
    | "INVITE"
    | "PROGRESS"
    | "TOURNAMENT"
    | "DAILY_ENTRY"
    | "REFUND"
    | "WELCOME_BONUS"
    | "SMS_BONUS"
    | "WHEEL_FORTUNE"
    | "CASH_OUT"
    | "RETAIL_PAYMENT"
    | "DEPOSIT";

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  updateLevel!: boolean;
}

export { BalanceTransactionCreateInput as BalanceTransactionCreateInput };
