/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProductService } from "../product.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductCreateInput } from "./ProductCreateInput";
import { Product } from "./Product";
import { ProductFindManyArgs } from "./ProductFindManyArgs";
import { ProductWhereUniqueInput } from "./ProductWhereUniqueInput";
import { ProductUpdateInput } from "./ProductUpdateInput";
import { BalanceTransactionFindManyArgs } from "../../balanceTransaction/base/BalanceTransactionFindManyArgs";
import { BalanceTransaction } from "../../balanceTransaction/base/BalanceTransaction";
import { BalanceTransactionWhereUniqueInput } from "../../balanceTransaction/base/BalanceTransactionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductControllerBase {
  constructor(
    protected readonly service: ProductService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Product })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProduct(
    @common.Body() data: ProductCreateInput
  ): Promise<Product> {
    return await this.service.createProduct({
      data: {
        ...data,

        shop: data.shop
          ? {
              connect: data.shop,
            }
          : undefined,
      },
      select: {
        amountToReceiveInCents: true,
        bonusCode: true,
        bonusSpins: true,
        bonusTotalInCents: true,
        createdAt: true,
        description: true,
        discountInCents: true,
        id: true,
        isPromo: true,
        priceInCents: true,

        shop: {
          select: {
            id: true,
          },
        },

        title: true,
        totalDiscountInCents: true,
        typeField: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Product] })
  @ApiNestedQuery(ProductFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async products(@common.Req() request: Request): Promise<Product[]> {
    const args = plainToClass(ProductFindManyArgs, request.query);
    return this.service.products({
      ...args,
      select: {
        amountToReceiveInCents: true,
        bonusCode: true,
        bonusSpins: true,
        bonusTotalInCents: true,
        createdAt: true,
        description: true,
        discountInCents: true,
        id: true,
        isPromo: true,
        priceInCents: true,

        shop: {
          select: {
            id: true,
          },
        },

        title: true,
        totalDiscountInCents: true,
        typeField: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async product(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    const result = await this.service.product({
      where: params,
      select: {
        amountToReceiveInCents: true,
        bonusCode: true,
        bonusSpins: true,
        bonusTotalInCents: true,
        createdAt: true,
        description: true,
        discountInCents: true,
        id: true,
        isPromo: true,
        priceInCents: true,

        shop: {
          select: {
            id: true,
          },
        },

        title: true,
        totalDiscountInCents: true,
        typeField: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProduct(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() data: ProductUpdateInput
  ): Promise<Product | null> {
    try {
      return await this.service.updateProduct({
        where: params,
        data: {
          ...data,

          shop: data.shop
            ? {
                connect: data.shop,
              }
            : undefined,
        },
        select: {
          amountToReceiveInCents: true,
          bonusCode: true,
          bonusSpins: true,
          bonusTotalInCents: true,
          createdAt: true,
          description: true,
          discountInCents: true,
          id: true,
          isPromo: true,
          priceInCents: true,

          shop: {
            select: {
              id: true,
            },
          },

          title: true,
          totalDiscountInCents: true,
          typeField: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProduct(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    try {
      return await this.service.deleteProduct({
        where: params,
        select: {
          amountToReceiveInCents: true,
          bonusCode: true,
          bonusSpins: true,
          bonusTotalInCents: true,
          createdAt: true,
          description: true,
          discountInCents: true,
          id: true,
          isPromo: true,
          priceInCents: true,

          shop: {
            select: {
              id: true,
            },
          },

          title: true,
          totalDiscountInCents: true,
          typeField: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/shopTransaction")
  @ApiNestedQuery(BalanceTransactionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BalanceTransaction",
    action: "read",
    possession: "any",
  })
  async findShopTransaction(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<BalanceTransaction[]> {
    const query = plainToClass(BalanceTransactionFindManyArgs, request.query);
    const results = await this.service.findShopTransaction(params.id, {
      ...query,
      select: {
        amount: true,
        bonusIdUsed: true,
        cashierAccountId: true,
        cashierAvatar: true,
        cashierId: true,
        cashiername: true,
        channel: true,
        createdAt: true,
        currency: true,
        direction: true,
        id: true,
        paymentMethod: true,
        personAvatar: true,
        personId: true,
        personname: true,

        playerAccount: {
          select: {
            id: true,
          },
        },

        playerAccountBalanceAfterTransaction: true,

        product: {
          select: {
            id: true,
          },
        },

        salesCommission: true,

        shop: {
          select: {
            id: true,
          },
        },

        shopBalanceAfterTransaction: true,
        status: true,
        totalInCents: true,
        type: true,
        updateLevel: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/shopTransaction")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async connectShopTransaction(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: BalanceTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      shopTransaction: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/shopTransaction")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async updateShopTransaction(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: BalanceTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      shopTransaction: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/shopTransaction")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async disconnectShopTransaction(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: BalanceTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      shopTransaction: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }
}
